In [ ]:
#1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv
#dataset.
#2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall
#on the given dataset.

In [ ]:
#Problem Analysis
#To implement the Naive Bayes Classification, we shall use a very famous Iris Flower
#Dataset that consists of 3 classes of flowers.
#In this, there are 4 independent variables namely the, sepal_length, sepal_width,
#petal_length and petal_width.
#The dependent variable is the species which we will predict using the four independent
#features of the flowers.
#Using the various features of the flower (independent variables),
#we have to classify a given flower using Naive Bayes Classification model.

In [2]:
#Step 1: Importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#Step 2: Importing the dataset
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')
dataset

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
#Step 3:Describe dataset,See dimension and Explore dataset
dataset.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
dataset.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
dataset.shape

(150, 5)

In [8]:
X = dataset.iloc[:,:4].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [10]:
y = dataset['species'].values
y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica'], dtype=object)

In [11]:
#Step 4: Splitting the dataset into the Training set and Test set
#Here, we have the test_size=0.2,
#which means that 20% of the dataset will be used for testing purpose as the test set and
#the remaining 80% will be used as the training set for training the Naive Bayes
#classification model.

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
#Step 5: Feature Scaling
#The dataset is scaled down to a smaller range using the Feature Scaling option. In this,
#both the X_train and X_test values are scaled down to smaller values to improve the speed
#of the program.

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[-0.21060001, -0.11337315,  0.21062104, -0.04916183],
       [-1.07777651,  0.79361203, -1.35454448, -1.36014409],
       [-0.33448237, -0.79361203,  0.21062104,  0.08193639],
       [-1.20165887,  0.11337315, -1.35454448, -1.49124231],
       [ 0.53269414, -1.24710462,  0.67437379,  0.86852574],
       [-0.8300118 ,  0.79361203, -1.41251358, -1.36014409],
       [-0.21060001, -0.56686573,  0.15265195,  0.08193639],
       [-1.57330594,  0.79361203, -1.41251358, -1.22904586],
       [ 1.02822357,  0.56686573,  1.08015744,  1.6551151 ],
       [-1.32554123, -0.11337315, -1.41251358, -1.49124231],
       [ 0.28492942, -0.56686573,  0.09468285,  0.08193639],
       [-0.95389415,  0.79361203, -1.35454448, -1.36014409],
       [-0.8300118 ,  2.38083608, -1.35454448, -1.49124231],
       [-1.07777651, -2.38083608, -0.19516261, -0.31135829],
       [ 1.77151772, -0.34011944,  1.427972  ,  0.73742752],
       [-1.32554123,  0.11337315, -1.29657539, -1.36014409],
       [ 0.28492942, -1.02035832,  1.02218835,  0.21303462],
       [ 0.6565765 ,  0.11337315,  0.96421925,  0.73742752],
       [ 0.16104707, -1.9273435 ,  0.09468285, -0.31135829],
       [-1.20165887,  0.11337315, -1.35454448, -1.49124231],
       [-0.45836472,  2.60758238, -1.41251358, -1.36014409],
       [-0.08671765, -0.79361203,  0.03671376, -0.04916183],
       [ 0.28492942, -0.11337315,  0.61640469,  0.73742752],
       [ 0.6565765 ,  0.34011944,  0.84828107,  1.39291865],
       [-0.8300118 , -0.79361203,  0.03671376,  0.21303462],
       [-0.21060001, -0.34011944,  0.21062104,  0.08193639],
       [-0.08671765, -0.56686573,  0.73234288,  1.52401687],
       [-0.21060001,  3.06107497, -1.35454448, -1.09794764],
       [ 1.15210593,  0.34011944,  1.19609563,  1.39291865],
       [ 0.40881178, -0.56686573,  0.5584356 ,  0.73742752],
       [ 1.15210593, -0.11337315,  0.96421925,  1.13072219],
       [ 1.02822357, -0.11337315,  0.67437379,  0.60632929],
       [ 0.53269414,  0.56686573,  1.25406472,  1.6551151 ],
       [-1.32554123,  0.79361203, -1.12266811, -1.36014409],
       [ 0.90434121, -0.34011944,  0.44249741,  0.08193639],
       [ 0.6565765 , -0.34011944,  0.26859013,  0.08193639],
       [-0.08671765, -0.79361203,  0.73234288,  0.86852574],
       [ 0.03716471, -0.11337315,  0.21062104,  0.34413284],
       [-1.82107066,  0.34011944, -1.47048267, -1.36014409],
       [-0.58224708,  1.47385091, -1.35454448, -1.36014409],
       [-1.57330594,  0.34011944, -1.41251358, -1.36014409],
       [ 0.16104707, -0.79361203,  0.73234288,  0.47523107],
       [-0.08671765,  2.15408979, -1.52845176, -1.36014409],
       [-0.95389415,  0.56686573, -1.2386063 , -0.96684941],
       [-0.58224708,  1.9273435 , -1.47048267, -1.09794764],
       [ 0.53269414, -1.24710462,  0.61640469,  0.34413284],
       [-1.07777651, -0.11337315, -1.29657539, -1.36014409],
       [ 0.16104707, -0.34011944,  0.38452832,  0.34413284],
       [-0.95389415,  1.7005972 , -1.29657539, -1.36014409],
       [ 1.27598828,  0.11337315,  0.73234288,  1.39291865],
       [ 1.27598828,  0.11337315,  0.90625016,  1.13072219],
       [-0.33448237, -0.56686573,  0.61640469,  0.99962397],
       [-0.95389415,  1.47385091, -1.35454448, -1.09794764],
       [ 0.78045885, -0.11337315,  0.96421925,  0.73742752],
       [-0.8300118 ,  1.02035832, -1.35454448, -1.36014409],
       [-0.95389415,  1.02035832, -1.41251358, -1.36014409],
       [-1.07777651,  0.79361203, -1.29657539, -1.09794764],
       [ 1.523753  , -0.11337315,  1.19609563,  1.13072219],
       [ 1.27598828,  0.11337315,  0.61640469,  0.34413284],
       [ 2.51481186,  1.7005972 ,  1.4859411 ,  0.99962397],
       [-0.70612944,  1.47385091, -1.35454448, -1.36014409],
       [ 0.03716471,  0.34011944,  0.5584356 ,  0.73742752],
       [ 1.02822357, -0.11337315,  0.79031197,  1.39291865],
       [ 0.78045885,  0.34011944,  0.73234288,  0.99962397],
       [ 0.78045885, -0.11337315,  1.13812653,  1.26182042],
       [ 0.40881178,  0.79361203,  0.90625016,  1.39291865],
       [ 0.16104707, -1.9273435 ,  0.67437379,  0.34413284],
       [-0.95389415, -1.24710462, -0.48500808, -0.18026006],
       [ 1.02822357,  0.11337315,  0.50046651,  0.34413284],
       [-0.58224708,  0.79361203, -1.2386063 , -1.36014409],
       [ 0.03716471, -0.11337315,  0.73234288,  0.73742752],
       [ 1.64763536,  0.34011944,  1.25406472,  0.73742752],
       [ 1.02822357,  0.11337315,  0.32655923,  0.21303462],
       [ 0.78045885, -0.56686573,  0.44249741,  0.34413284],
       [-0.33448237, -0.34011944, -0.13719352,  0.08193639],
       [-0.45836472, -1.7005972 ,  0.09468285,  0.08193639],
       [ 1.64763536,  1.24710462,  1.31203382,  1.6551151 ],
       [-0.21060001, -1.24710462,  0.67437379,  0.99962397],
       [-0.21060001, -0.56686573,  0.38452832,  0.08193639],
       [-0.95389415,  1.7005972 , -1.35454448, -1.22904586],
       [-1.20165887, -1.47385091, -0.3111008 , -0.31135829],
       [-0.58224708,  0.79361203, -1.35454448, -1.09794764],
       [-1.20165887,  0.11337315, -1.35454448, -1.49124231],
       [ 1.02822357, -1.24710462,  1.13812653,  0.73742752],
       [-0.08671765, -0.79361203,  0.73234288,  0.86852574],
       [ 1.39987064,  0.34011944,  0.50046651,  0.21303462],
       [-0.33448237, -0.11337315,  0.38452832,  0.34413284],
       [ 0.28492942, -0.34011944,  0.50046651,  0.21303462],
       [ 0.53269414, -0.34011944,  1.02218835,  0.73742752],
       [-1.07777651,  1.24710462, -1.41251358, -1.36014409],
       [ 0.16104707, -0.11337315,  0.5584356 ,  0.73742752],
       [-0.33448237, -1.24710462,  0.03671376, -0.18026006],
       [-1.07777651, -1.7005972 , -0.3111008 , -0.31135829],
       [-0.08671765, -0.79361203,  0.15265195, -0.31135829],
       [-1.32554123, -0.11337315, -1.41251358, -1.22904586],
       [-0.21060001,  1.7005972 , -1.2386063 , -1.22904586],
       [ 1.02822357,  0.11337315,  1.02218835,  1.52401687],
       [-1.6971883 , -1.7005972 , -1.47048267, -1.22904586],
       [-0.45836472, -1.47385091, -0.02125533, -0.18026006],
       [-0.58224708, -0.11337315,  0.38452832,  0.34413284],
       [ 1.27598828,  0.34011944,  1.08015744,  1.39291865],
       [ 0.78045885, -0.11337315,  0.79031197,  0.99962397],
       [ 1.89540007, -0.56686573,  1.31203382,  0.86852574],
       [ 2.14316479, -0.11337315,  1.60187928,  1.13072219],
       [ 0.40881178, -1.9273435 ,  0.38452832,  0.34413284],
       [ 0.28492942, -0.11337315,  0.44249741,  0.21303462],
       [-0.45836472, -1.24710462,  0.09468285,  0.08193639],
       [-1.32554123,  0.79361203, -1.29657539, -1.36014409],
       [-0.95389415,  1.02035832, -1.41251358, -1.22904586],
       [-0.95389415,  1.7005972 , -1.12266811, -1.09794764],
       [-1.20165887, -1.24710462,  0.38452832,  0.60632929],
       [ 0.40881178, -0.34011944,  0.26859013,  0.08193639],
       [ 0.53269414,  0.56686573,  0.50046651,  0.47523107],
       [ 2.26704715, -1.02035832,  1.77578656,  1.39291865],
       [-1.44942359,  0.34011944, -1.29657539, -1.36014409],
       [ 1.64763536, -0.11337315,  1.13812653,  0.47523107],
       [ 0.6565765 , -0.56686573,  1.02218835,  1.13072219],
       [ 2.26704715, -0.11337315,  1.31203382,  1.39291865],
       [ 0.6565765 , -0.79361203,  0.84828107,  0.86852574],
       [-1.82107066, -0.34011944, -1.41251358, -1.36014409]])

In [14]:
X_test

array([[-0.58224708,  1.9273435 , -1.2386063 , -1.09794764],
       [-1.44942359,  0.34011944, -1.47048267, -1.36014409],
       [ 0.28492942, -0.56686573,  0.50046651, -0.04916183],
       [ 1.02822357,  0.56686573,  1.08015744,  1.13072219],
       [-1.07777651,  1.02035832, -1.47048267, -1.22904586],
       [-0.45836472,  1.02035832, -1.47048267, -1.36014409],
       [ 1.15210593, -0.56686573,  0.5584356 ,  0.21303462],
       [-0.08671765, -1.02035832,  0.09468285, -0.04916183],
       [-1.94495302, -0.11337315, -1.58642086, -1.49124231],
       [ 2.26704715, -0.56686573,  1.65984838,  0.99962397],
       [ 0.53269414,  0.79361203,  1.02218835,  1.52401687],
       [ 0.53269414, -0.79361203,  0.61640469,  0.73742752],
       [-0.45836472, -1.02035832,  0.32655923, -0.04916183],
       [-0.33448237, -0.11337315,  0.15265195,  0.08193639],
       [ 0.6565765 , -0.56686573,  1.02218835,  1.26182042],
       [ 0.53269414, -0.56686573,  0.73234288,  0.34413284],
       [-1.57330594,  0.11337315, -1.35454448, -1.36014409],
       [ 0.53269414, -1.7005972 ,  0.32655923,  0.08193639],
       [ 0.6565765 ,  0.34011944,  0.38452832,  0.34413284],
       [-1.07777651,  0.34011944, -1.52845176, -1.36014409],
       [ 2.26704715,  1.7005972 ,  1.65984838,  1.26182042],
       [-1.07777651,  0.56686573, -1.41251358, -1.36014409],
       [ 0.16104707,  0.79361203,  0.38452832,  0.47523107],
       [-1.57330594,  1.24710462, -1.64438995, -1.36014409],
       [-1.20165887, -0.11337315, -1.41251358, -1.36014409],
       [-0.21060001, -1.02035832, -0.19516261, -0.31135829],
       [-1.82107066, -0.11337315, -1.47048267, -1.36014409],
       [ 0.90434121, -0.11337315,  0.32655923,  0.21303462],
       [-1.07777651,  1.02035832, -1.29657539, -0.83575119],
       [-0.45836472, -1.47385091, -0.07922443, -0.31135829]])

In [ ]:
#Step 6: Training the Naive Bayes Classification model on the Training Set
#n this step, we introduce the class GaussianNB that is used from the sklearn.naive_bayes
#library.
#Here, we have used a Gaussian model, there are several other models such as Bernoulli,
#Categorical and Multinomial.

In [15]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [16]:
#Step 6: Predicting the Test set results

y_pred = classifier.predict(X_test)
y_pred

array(['setosa', 'setosa', 'versicolor', 'virginica', 'setosa', 'setosa',
       'versicolor', 'versicolor', 'setosa', 'virginica', 'virginica',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'versicolor',
       'setosa', 'versicolor', 'versicolor', 'setosa', 'virginica',
       'setosa', 'versicolor', 'setosa', 'setosa', 'versicolor', 'setosa',
       'versicolor', 'setosa', 'versicolor'], dtype='<U10')

In [18]:
#Step 7: Confusion Matrix and Accuracy
#This is a step that is mostly used in classification techniques.
#In this, we see the Accuracy of the trained model and plot the confusion matrix.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[12,  0,  0],
       [ 0, 11,  0],
       [ 0,  1,  6]], dtype=int64)

In [19]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.9666666666666667

In [20]:
#Step 8: Comparing the Real Values with Predicted Values

In [21]:
df = pd.DataFrame({'Real Values':y_test,'Predicted Values':y_pred})
df

   Real Values Predicted Values
0       setosa           setosa
1       setosa           setosa
2   versicolor       versicolor
3    virginica        virginica
4       setosa           setosa
5       setosa           setosa
6   versicolor       versicolor
7   versicolor       versicolor
8       setosa           setosa
9    virginica        virginica
10   virginica        virginica
11   virginica        virginica
12  versicolor       versicolor
13  versicolor       versicolor
14   virginica        virginica
15   virginica       versicolor
16      setosa           setosa
17  versicolor       versicolor
18  versicolor       versicolor
19      setosa           setosa
20   virginica        virginica
21      setosa           setosa
22  versicolor       versicolor
23      setosa           setosa
24      setosa           setosa
25  versicolor       versicolor
26      setosa           setosa
27  versicolor       versicolor
28      setosa           setosa
29  versicolor       versicolor